changelog + version bump
SumoLogic/fluentd-output-sumologic pull request #97
Opened 2024-10-04 17:27 UTC by michaelwang13

Prepare for ruby gem version 1.9.1

2024-10-07 18:31 UTC, echlebek requested changes
Thanks for submitting a release PR, however I think that we need to release 1.10.0, as the previous commit added a new feature. Can you change it?

2024-10-08 12:11 UTC, michaelwang13 commented
I wasn't sure of the versioning conventions. Changed

2024-10-09 05:52 UTC, echlebek approved these changes

2024-10-09 05:52 UTC, echlebek commented
Thanks so much for the contribution.

2024-10-09 05:54 UTC, merged